export const AREA_OPTIONS = [
    'Front-End Development',
    'React',
    'Angular',
    'Vue',
    'Svelte',
    'TypeScript',
    'jQuery',
    'HTML/CSS',
    'WebAssembly',
    'Back-End Development',
    'Node.js',
    'Express.js',
    'NestJS',
    'Spring',
    'Django',
    'Flask',
    'Ruby on Rails',
    'ASP.NET',
    'Go',
    'PHP',
    'Laravel',
    'Java',
    'Scala',
    'Elixir',
    'Python',
    'C#',
    'Kotlin',
    'RUST',
    'GraphQL',
    'Data Science',
    'Database Management',
    'SQL',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Machine Learning',
    'Computer Vision',
    'DevOps',
    'Network Management',
    'Security and Compliance',
    'Version Control',
    'CI/CD Pipeline',
    'System Administration',
    'Testing',
    'Unit Testing',
    'Integration Testing',
    'End-to-end Testing',
    'Accessibility Testing',
    'API Testing',
    'Manual Testing',
    'Security Testing',
    'Functional Testing',
    'Performance Testing',
    'Unity',
    'Unreal Engine',
    'Game Development',
    '2D Gaming',
    '3D Gaming',
    'Mobile App Development',
    'Native Android',
    'Native iOS',
    'Flutter',
    'React Native',
    'Network Engineering',
    'Routing and Switching',
    'Data Center Networking',
    'Network Automation',
    'Cloud Networking',
    'Security',
    'UI/UX Design',
    'Graphic Design',
    'Interaction Design',
    'Prototyping',
];
